title: Niklas Riekenbrauck
email: nikriek@gmail.com
description: "Blog & portfolio of a hacker"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.nikriek.de" # the base hostname & protocol for your site
twitter_username: nikriek
github_username: nikriek

# Build settings
markdown: kramdown
exclude:
  - "bower_components"
  - "bower.json"
plugins:
  - jekyll-paginate
  - jekyll-sitemap
paginate: 40
